CA-186 Adds KMS Interface Endpoint.
Datatamer/terraform-aws-networking pull request #19
Opened 2022-04-07 18:13 UTC by fvazquez-caylent

* Adds KMS VPC Interface Endpoint.

2022-04-08 14:22 UTC, souza-dan commented on examples/minimal/sg_web.tf
> +  source = "git::git@github.com:Datatamer/terraform-aws-security-groups.git?ref=1.2.0"
Latest release of the security groups module is 1.0.0:
https://github.com/Datatamer/terraform-aws-security-groups/releases
```suggestion
  source = "git::git@github.com:Datatamer/terraform-aws-security-groups.git?ref=1.0.0"
```

2022-04-08 14:22 UTC, souza-dan commented on vpc-endpoints.tf
> +    cidr_blocks = [var.compute_subnet_cidr_block]
Would the application and data subnets benefit from being able to use this endpoint as well?

2022-04-12 18:26 UTC, franco-caylent commented on vpc-endpoints.tf
> +    cidr_blocks = [var.compute_subnet_cidr_block]
If we decide to implement KMS encryption for tamr-vm yes, not so sure about RDS but i'd suppose yes.

2022-04-12 18:27 UTC, franco-caylent requested changes
LGTM, please update the security groups module before merging

2022-04-15 21:26 UTC, souza-dan approved these changes
LGTM

2022-04-18 14:27 UTC, franco-caylent approved these changes
LGTM

2022-04-18 14:28 UTC, merged